/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "dashboard": [],
    "analytics.index": [],
    "reservations.show": [
        {
            "name": "reservation",
            "required": true
        }
    ],
    "reservations.messages.index": [
        {
            "name": "reservation",
            "required": true
        }
    ],
    "reservations.bulk-status": [],
    "reservation-replies.approve": [
        {
            "name": "reply",
            "required": true,
            "binding": "id"
        }
    ],
    "reservation-replies.cancel-auto-send": [
        {
            "name": "reply",
            "required": true,
            "binding": "id"
        }
    ],
    "restaurants.send-mode.killswitch": [
        {
            "name": "restaurant",
            "required": true,
            "binding": "id"
        }
    ],
    "public.reservations.create": [
        {
            "name": "restaurant",
            "required": true,
            "binding": "slug"
        }
    ],
    "public.reservations.store": [
        {
            "name": "restaurant",
            "required": true,
            "binding": "slug"
        }
    ],
    "public.reservations.thanks": [
        {
            "name": "restaurant",
            "required": true,
            "binding": "slug"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "settings.send-mode.edit": [],
    "settings.send-mode.update": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
