/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "onboarding.accept": [
        {
            "name": "token",
            "required": true
        }
    ],
    "onboarding.accept.store": [
        {
            "name": "token",
            "required": true
        }
    ],
    "onboarding.wizard": [],
    "onboarding.restaurant.update": [],
    "onboarding.hours.update": [],
    "onboarding.tables.store": [],
    "onboarding.tonality.update": [],
    "onboarding.team.store": [],
    "onboarding.pending": [],
    "dashboard": [],
    "analytics.index": [],
    "exports.store": [],
    "exports.download": [
        {
            "name": "token",
            "required": true
        }
    ],
    "reservations.quick.create": [],
    "reservations.quick.store": [],
    "reservations.show": [
        {
            "name": "reservation",
            "required": true
        }
    ],
    "reservations.messages.index": [
        {
            "name": "reservation",
            "required": true
        }
    ],
    "reservations.bulk-status": [],
    "reservations.bulk-delete": [],
    "reservation-replies.approve": [
        {
            "name": "reply",
            "required": true,
            "binding": "id"
        }
    ],
    "reservation-replies.cancel-auto-send": [
        {
            "name": "reply",
            "required": true,
            "binding": "id"
        }
    ],
    "reservation-replies.mark-shadow-compared": [
        {
            "name": "reply",
            "required": true,
            "binding": "id"
        }
    ],
    "restaurants.send-mode.killswitch": [
        {
            "name": "restaurant",
            "required": true,
            "binding": "id"
        }
    ],
    "tables.availability": [],
    "tables.index": [],
    "tables.store": [],
    "tables.update": [
        {
            "name": "table",
            "required": true,
            "binding": "id"
        }
    ],
    "tables.destroy": [
        {
            "name": "table",
            "required": true,
            "binding": "id"
        }
    ],
    "public.reservations.create": [
        {
            "name": "restaurant",
            "required": true,
            "binding": "slug"
        }
    ],
    "public.reservations.store": [
        {
            "name": "restaurant",
            "required": true,
            "binding": "slug"
        }
    ],
    "public.reservations.thanks": [
        {
            "name": "restaurant",
            "required": true,
            "binding": "slug"
        }
    ],
    "gdpr.self-service": [
        {
            "name": "reservation",
            "required": true,
            "binding": "id"
        }
    ],
    "gdpr.self-service.delete": [
        {
            "name": "reservation",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "settings.send-mode.edit": [],
    "settings.send-mode.update": [],
    "settings.notifications.edit": [],
    "settings.notifications.update": [],
    "settings.ai-key.edit": [],
    "settings.ai-key.update": [],
    "settings.smtp.edit": [],
    "settings.smtp.update": [],
    "settings.imap.edit": [],
    "settings.imap.update": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
